version: "3"
services:
  app:
    build:
      context: .
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - app-media:/files/media
      - app-static:/files/static
    image: partnersinbahamas/rick-morty-app
    command: >
      sh -c "sleep 5 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5436:5432"
    env_file:
      - .env.docker
    volumes:
      - app-db:$PGDATA

  redis:
    image: "redis:alpine"

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery -A app worker -l INFO"
    depends_on:
      - app
      - db
      - redis
    restart: on-failure
    env_file:
      - .env.docker

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: "celery -A app beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      - app
      - db
      - redis
    restart: on-failure
    env_file:
      - .env.docker

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    command: "celery -A app flower --address=0.0.0.0"
    depends_on:
      - celery
    env_file:
      - .env.docker

volumes:
  app-db:
  app-media:
  app-static:
